import java.io.File

/**
 * Script automatizado para generar el mapeo completo de síntomas a enfermedades
 * 
 * Este script:
 * 1. Lee la lista completa de síntomas del usuario
 * 2. Mapea cada síntoma con las enfermedades correspondientes
 * 3. Genera un archivo JSON con el mapeo completo
 * 4. Proporciona estadísticas del mapeo
 */

// Lista completa de síntomas normalizados del usuario
val sintomasUsuario = listOf(
    "ABCESOS CUTANEOS", "ABCESOS EN BAZO", "ABCESOS EN RIÑONES", "ABCESOS HEPATICOS", "ABCESOS PULMONARES",
    "ABDOMEN PURPURA", "ABORTO", "ABORTO EN CUALQUIER ETAPA", "ABORTO TERCER TERCIO", "ABSCESOS CUTANEOS",
    "ADELGAZAMIENTO DE PAREDES INTESTINALES", "ADENOMATOSIS INTESTINAL", "ADHERENCIAS EN PULMON Y COSTILLAS",
    "ADHERENCIAS FIBRINONECROTICAS EN ABDOMEN", "ADIPSIA", "AGALAXIA", "AMONTONAMIENTO DE CERDOS", "ANEMIA",
    "ANESTRO", "ANOREXIA", "APARENCIA SUCIA DEL LECHON", "AREAS DE CONSOLIDACION PURPURA-GRIS",
    "AREAS DE NECROSIS CIRCULARES Y CONCENTRICAS EN INTESTINOS", "ARTRITIS", "ARTRITIS PURULENTA",
    "ARTRITIS SUPURATIVA", "ASCITIS", "ATAXIA", "ATROFIA DE VELLOSIDADES INTESTINALES", "ATROFIA TESTICULAR",
    "BAJO NUMERO DE NACIDOS VIVOS", "BANDAS CICATRICIALES EN PULMONES", "BOTONES PESTOSOS EN INTESTINO DELGADO",
    "BRAQUIGNATISMO SUPERIOR", "BRONCONEUMONIA", "BRONCONEUMONIA CATARRAL PURULENTA", "BRONCONEUMONIA PURULENTA",
    "BRONCONEUMONIA SUPURATIVA LOBULAR", "BRONQIOLITIS EXUDATIVA", "BRONQUITIS", "BRONQUITIS SUPURATIVA",
    "BULLAS PULMONARES", "BURSITIS", "CABEZA AGACHADA", "CALAMBRES ABDOMINALES", "CANCER", "CAQUEXIA",
    "CEGUERA", "CELO SILENCIO", "CELO TARDIO POSTDESTETE", "CERDAS PRIMERIZAS SON MÁS AFECTADAS", "CIANOSIS",
    "CIANOSIS EN PECHO Y ESTOMAGO", "COJERA", "COLITIS CATARRAL", "CONGESTION Y EDEMA DE COLON", "CONGESTION PULMONAR",
    "CONJUNTIVITIS", "CONJUNTIVITIS DEL RECIEN NACIDO", "CONSOLIDACION CRÁNEO VENTRAL PURPURA-GRIS EN PULMONES",
    "CONSUMO DE ORINA", "CONVERSION ALIMENTICIA ELEVADA", "CONVULSIONES", "CORAZON BLANDO", "COSTRAS SECAS EN PIEL",
    "CRECIMIENTO LENTO", "DEBILIDAD", "DECOLORACION DEL MUSCULO DORSAL", "DECUBITO LATERAL", "DEFORMACION DE ARTICULACIONES",
    "DEPRESION", "DERMATITIS", "DERMATITIS HEMORRAGICA NECORTIZANTE", "DESCARGA NASAL", "DESCARGA NASAL SANGUINOLENTA",
    "DESCARGA VAGINAL COLOR CAFÉ-GRISASEO", "DESCARGA VAGINAL SANGUINOLENTA", "DESHIDRATACION", "DESMEDRO", "DESNUTRICION",
    "DIARREA", "DIARREA AGUDA AMARILLA", "DIARREA ACUOSA", "DIARREA ACUOSA AMARILLA", "DIARREA AMARILLA",
    "DIARREA AMARILLA LIQUIDA", "DIARREA BLANQUECINA", "DIARREA CAFÉ", "DIARREA COLOR ALQUITRAN", "DIARREA COLOR GRIS CEMENTO",
    "DIARREA CON SANGRE COLOR OBSCURO Y ALQUITRANADO", "DIARREA CON SANGRE Y MOCO", "DIARREA PERNICIOSA", "DIARREA GRASOSA",
    "DIARREA GRIS PASTOSA", "DIARREA HEMORRAGICA", "DIARREA MUCOSA O CREMOSA", "MANCHA DED DIARREA EN LA PIEL DEL PERINÉ",
    "DIARREA SANGUINOLENTA", "DIARREA VERDOSA", "DIARREA VERDOSA CON OLOR FETIDO", "DILATACION DEL INTESTINO DELGADO",
    "DILATACION GASTRICA", "DISMINUCION DE CRECIMIENTO", "DISNEA", "DISTENSION INTESTINAL HEMORRAGICA", "DISTENSION RENAL",
    "DOLOR ABDOMINAL", "ECCEMA CON SARNA", "EDEMA CONJUNTIVAL", "EDEMA DE COLON", "EDEMA DE EXTREMIDADES POSTERIORES",
    "EDEMA DE LENGUA", "EDEMA DE LINFONODULOS BRONQUIALES", "EDEMA DE LINFONODULOS ILEOCECALES", "EDEMA DE LINFONODULOS MESENTERICOS",
    "EDEMA DE VESICULA BILIAR", "EDEMA DEL MESOCOLON", "EDEMA ESCROTAL", "EDEMA FIBRINOHEMORRAGICO DE INTESTINO DELGADO",
    "EDEMA INTESTINAL", "EDEMA MESENTERICO", "EDEMA PALPEBRAL", "EDEMA PREPUCIAL", "EDEMA PULMONAR", "EDEMA RENAL",
    "EDEMA SUBCUTANEO", "EDEMA TESTICULAR", "EDEMA Y CONGESTION DEL MESENTERIO", "EMACIACION", "ENCEFALITIS",
    "ENCEFALOMALASIA FOCAL", "ENCEFALOMIELITIS", "ENCORVAMIENTO", "ENDOCARDITIS", "ENDOCARDITIS MURAL", "ENDOCARDITIS VALVULAR",
    "ENDOCARDITIS VEGETATIVA", "ENDOMETRITIS", "ENFISEMA DE YEYUNO", "ENFISEMA PULMONAR", "ENTERITIS", "ENTERITIS CATARRAL",
    "ENTERITIS FIBRINONECROTICA", "ENTEROCOLITIS", "EPICARDITIS FIBRINOPURULENTA", "EPIDIDIMITIS", "EPIFORA",
    "EPISTAXIS (HEMORRAGIA NASAL)", "EQUIMOSIS", "EQUIMOSIS CUTANEA", "EQUIMOSIS RENAL", "ERITEMA CUTANEO", "ESPASMOS",
    "ESPLENOMEGALIA", "ESPUMA BLANCA EN TRAQUEA", "ESPUMA SANGUINOLENTA", "ESTOMAGO CONGESTIONADO", "ESTORNUDO",
    "ESTREÑIMIENTO SEGUIDO DE DIARREA", "EXPULSION TARDIA DE LECHONES", "EXTRACCION DIFICIL DE PLACENTA RETENIDA",
    "EXUDADO MUCOSO EN TRAQUEA", "EXUDADO SANGUINOLENTO EN INTESTINO DELGADO", "EXUDADO SANGUINOLENTO EN INTESTINO GRUESO",
    "FALLA REPRODUCTIVA", "FIBRINA INTESTINAL", "FIEBRE", "FIEBRE (43°c)", "FRACTURAS OSEAS", "GANGLIOS RENALES AGRANDADOS HEMORRAGICOS",
    "GANGRENA GASEOSA", "HECES SECAS", "HEMORRAGIA CEREBRAL", "HEMORRAGIA DE LINFONODULOS PULMONARES", "HEMORRAGIA DEL CORDON UMBILICAL",
    "HEMORRAGIA ENDOMETRIAL", "HEMORRAGIA HEPATICA", "HEMORRAGIA OCULAR", "HEMORRAGIA PLACENTARIA", "HEMORRAGIA PULMONAR",
    "HEMORRAGIA RENAL", "HEMORRAGIA SUBCUTANEA", "HEMORRAGIA TESTICULAR", "HEMORRAGIAS VASCULARES (COLOR VIOLETA EN LA PIEL)",
    "HEPATITIS", "HEPATOMEGALIA", "HIDROPERICARDIO", "HIDROTORAX", "HINCHAZON DE CUELLO", "HINCHAZON DOLOROSA EN ESTOMAGO",
    "HIPEREMIA CUTANEA", "HIPEREXCITACION", "HIPERPLASIA DE LINFONODULOS", "HIPERTROFIA DEL APARATO REPRODUCTOR DE LA CERDA",
    "HIPOGALAXIA", "HIPOTERMIA", "ICTERICIA", "INCOORDINACION", "INFARTO DE VESICULA BILIAR", "INFARTO ESPLENICO",
    "INFARTOS VENOSOS EN CURVATURA MAYOR DEL ESTOMAGO", "INFERTILIDAD", "INFLAMACION HEMORRAGICA DE ESTOMAGO",
    "INFLAMACION HEMORRAGICA DE INTESTINO", "INTESTINO DELGADO ROJO OBSCURO", "INTESTINO DELGADO TRANSPARENTE",
    "IRRITACION PERIANAL", "MUERTE FETAL EN DISTINTAS EDADES", "LAGAÑEO", "LECHE SIN DIGERIR EN ESTOMAGO", "LECHONES MOMIFICADOS",
    "LECHONES NACIDOS BLANCOS", "LECHONES NACIDOS CON PATAS ABIERTAS (SPLAYLEGS)", "LECHONES NACIDOS DEBILES", "LECHONES NACIDOS MUERTOS",
    "LESION HORIZONTAL EN PEZUÑAS", "LESIONES MULTIFOCALES EN HIGADO", "LESIONES MULTIFOCALES EN PULMON", "LETARGIA", "LINFADENITIS",
    "LINFADENOMEGALIA", "LINFONODULOS INGUINALES GRANDES Y NEGROS", "LINFONODULOS MESENTERICOS EDEMATOSOS",
    "LINFONODULOS PULMONARES GRANDES Y NEGROS", "LINFONODULOS RENALES AGRANDADOS HEMORRAGICOS", "LIQUIDO SINOVIAL HEMORRAGICO",
    "LIQUIDO SINOVIAL PURULENTO", "LORDOSIS", "LOS LECHONES SE ACUESTAN SOBRE LA CERDA", "MALFORMACIONES FETALES",
    "MANCHAS BLANCAS (DE CAL) EN PLACENTA", "MANCHAS BLANCAS EN RIÑONES", "MANCHAS DE LECHE EN HIGADO", "MANCHAS HEMORRAGICAS EN LA PIEL",
    "MANCHAS MORADAS", "MANCHAS ROJAS", "MARCHA EN CIRCULOS", "MARCHA EN REVERSA", "MASTITIS", "MASTITIS INTERSTICIAL",
    "MENINGES ENGROSADAS", "MENINGITIS", "MENINGOENCEFALITIS", "METRITIS", "MIOCARDITIS", "MIOCARDITIS HEMORRAGICA",
    "MORTALIDAD DEL 100% EN LECHONES LACTANTES", "MORTINATOS", "MUERTE", "MUERTE FETAL EN DISTINTOS MOMENTOS",
    "MUERTE FETAL DESPUES DE LOS 70 DIAS DE GESTACION", "MUERTE SUBITA", "NECROSIS CUTANEA", "NECROSIS DE EPIGLOTIS",
    "NECROSIS DE LA COLA", "NECROSIS DE LAS OREJAS", "NECROSIS DEL INTESTINO GRUESO", "NECROSIS DEL MIOCARDIO",
    "NECROSIS DEL MUSCULO DORSAL", "NECROSIS EN LAS OREJAS", "NECROSIS ESPLENICA", "NECROSIS FOCAL DE HIGADO", "NECROSIS HEPATICA",
    "NECROSIS PANCREATICA", "NECROSIS PULMONAR", "NECROSIS PULMONAR BILATERAL", "NEFRITIS", "NEFRITIS INTERSTICIAL",
    "NEUMONIA BRONCO INTERSTICIAL", "NEUMONIA EMBOLICA", "NEUMONIA EOSINOFILICA", "NEUMONIA FIBRINO PURULENTA",
    "NEUMONIA FIBRINO-NECROTICA", "NEUMONIA HEMORRAGICA", "NEUMONIA INTERSTICIAL MULTIFOCAL", "NEUMONIA INTERSTICIAL",
    "NEUMOTORAX", "NISTAGMO", "OCLUSION INTESTINAL", "OJOS HUNDIDOS", "OLIGURIA", "OLOR ACIDO DEL EXCREMENTO", "ONFALITIS",
    "ONFALOFLEBITIS", "OPACIDAD DE CORNEA", "OPISTOTONO", "OREJA AZUL", "ORQUITIS", "OSCILACION DE LA CABEZA",
    "OSTEOMIELITIS PURULENTA", "PALIDEZ", "PANCREATITIS", "PARALISIS", "PARALISIS POSTERIOR", "PARED INTESTINAL ADELGAZADA (TRANSPARENTE)",
    "PARESIA", "PARTO PREMATURO", "PEDALEO", "PELO HIRSUTO", "PERDIDA DE PESO", "PERICARDITIS", "PERICARDITIS FIBRINOSA",
    "PERITONITIS", "PERITONITIS FIBRINOSA", "PETEQUIA ESPLENICA", "PETEQUIA CARDIACA", "PETEQUIA PULMONAR", "PETEQUIA RENAL",
    "PIEL APERGAMINADA Y SUCIA", "PIEL PALIDA", "PIEL SECA Y AGRIETADA", "PLACENTITIS", "PLEURESIA", "PLEURITIS",
    "PLEURITIS FIBRINOSA", "PLEURITIS SEROSA", "POLIARTRITIS", "POLIDIPSIA", "POLISEROSITIS", "POLISEROSITIS SEROFIBRINOSA",
    "POSICION PERRO SENTADO", "POSTRACIÓN", "POSTURA ANORMAL", "PRESENCIA DE GAS EN EL INTESTINO GRUESO",
    "PRESENCIA DE MOCO EN INTESTINO GRUESO", "PRESENCIA DE PUS SECUESTRADA", "PROLAPSO RECTAL", "PROLAPSO VAGINAL",
    "PSEUDOPREÑEZ", "PUNTOS BLANCOS EN RIÑONES", "QUEMOSIS", "RAQUITISMO", "RECHAZO DE ALIMENTO", "REDUCCIÓN DE CELO EN CERDAS",
    "REPETICIONES DE CELO 21-35 DIAS", "RETENCION PLACENTARIA", "RETRASO DEL CRECIMIENTO", "RETRASO EN LA FECHA DE PARTO",
    "RIGIDEZ MUSCULAR", "RONCHAS ROJIZAS", "SANGRE EN LA ORINA", "SEPTICEMIA", "SIALORREA", "SINOVITIS", "SORDERA",
    "SUPRESION INMUNOLOGICA", "TAQUICARDIA", "TAQUIPNEA", "TEMBLORES", "TENDINITIS", "TENESMO", "TIFLITIS NECROTICA",
    "TIFLOCOLITIS", "TONSILITIS NECROTICA", "TORSION DEL TABIQUE NASAL", "TOS", "TOS ASMATICA", "TOS CRONICA SECA",
    "TOS DE AHOGO", "TOS PAROXISTICA", "TOS PRODUCTIVA", "TOS SECA", "TRAQUEITIS", "TREMOR CONGENITO", "TROMBOSIS CORONARIA",
    "TROMBOSIS DE VASOS SANGUINEOS DEL PULMON", "ULCERACION FOCAL DE INTESTINO DELGADO", "ULCERAS BOTONOSAS EN INTESTINO DELGADO Y GRUESO",
    "ULCERAS EN LA PIEL", "ULCERAS ORALES", "URETRA PURULENTA", "URETRITIS", "URTICARIA ROMBOIDE", "VARIACION DEL TAMAÑO DE LA CAMADA",
    "VEJIGA ENGROSADA", "VEJIGA HEMORRAGICA", "VEJIGA ULCEROSA", "VESICULA BILIAR HEMORRAGICA", "VESICULA BILIAR INFLAMADA COLOR VERDE OBSCURO",
    "VIENTRE PROMINENTE", "VOMITO", "VOMITO BLANQUECINO", "VOMITO CON MANCHAS DE SANGRE", "VULVOVAGINITIS"
)

// Base de datos de enfermedades y sus síntomas (extraída de DiseaseData.kt)
val enfermedadesConSintomas = mapOf(
    "Estreptococosis" to listOf(
        "FIEBRE (40°c-42°c)", "ANOREXIA", "DEPRESION", "POSTRACIÓN", "ATAXIA", "COJERA", "ARTRITIS",
        "OPISTOTONO", "CABEZA AGACHADA", "CONVULSIONES", "DISNEA", "CEGUERA", "SORDERA", "PEDALEO",
        "NISTAGMO", "SEPTICEMIA", "RIGIDEZ MUSCULAR", "MARCHA EN CIRCULOS", "PELO HIRSUTO", "TEMBLORES",
        "DECUBITO LATERAL", "ARTRITIS PURULENTA", "BRONCONEUMONIA PURULENTA", "MIOCARDITIS HEMORRAGICA",
        "POLISEROSITIS", "ENDOCARDITIS VALVULAR", "PERICARDITIS", "MENINGITIS", "NEUMONIA INTERSTICIAL"
    ),
    "Pleuroneumonia" to listOf(
        "FIEBRE (41.5°c)", "ANOREXIA", "TOS DE AHOGO", "DISNEA", "LETARGIA", "DEPRESION", "CIANOSIS",
        "VOMITO", "ADIPSIA", "POSICION PERRO SENTADO", "MUERTE SÚBITA", "TAQUIPNEA", "DISMINUCION DE CRECIMIENTO",
        "EDEMA PULMONAR", "HEPATOMEGALIA", "ESPLENOMEGALIA", "ESPUMA SANGUINOLENTA", "PLEURITIS FIBRINOSA",
        "NEUMONIA FIBRINO-NECROTICA", "TRAQUEITIS", "NEUMONIA HEMORRAGICA", "NECROSIS PULMONAR BILATERAL",
        "NECROSIS HEPATICA", "NECROSIS ESPLENICA", "NEUMOTORAX", "BULLAS PULMONARES", "EXUDADO MUCOSO EN TRAQUEA"
    ),
    "PRRS" to listOf(
        "FIEBRE (39°c-40°c)", "ANOREXIA", "TOS PRODUCTIVA", "ESTORNUDOS", "LETARGIA", "CIANOSIS",
        "CONJUNTIVITIS", "AGALAXIA", "MASTITIS", "ANESTRO", "ABORTO TERCER TERCIO", "FALLA REPRODUCTIVA",
        "REPETICIONES DE CELO 21-35 DIAS", "PARTO PREMATURO", "BAJO NUMERO DE NACIDOS VIVOS", "LECHONES MOMIFICADOS",
        "LECHONES NACIDOS MUERTOS", "LECHONES NACIDOS DEBILES", "HIPEREMIA CUTANEA", "ERITEMA CUTANEO EN OREJA",
        "ASCITIS", "QUEMOSIS GRAVE", "CELO TARDIO POSTDESTETE", "RETRASO DE CRECIMIENTO",
        "DIARREA CONSTANTE QUE NO CEDE EN LECHONES", "HEMORRAGIA DEL CORDON UMBILICAL",
        "NEUMONIA INTERSTICIAL MULTIFOCAL", "LINFONODULOS INGUINALES GRANDES Y NEGROS",
        "LINFONODULOS PULMONARES GRANDES Y NEGROS", "HIDROTORAX", "PETEQUIA PULMONAR", "MIOCARDITIS",
        "ENCEFALITIS", "MUERTE SÚBITA"
    ),
    "Circovirus" to listOf(
        "FIEBRE (41.5°c)", "POSTRACION", "EMACIACION", "ATAXIA", "ICTERICIA", "DESMEDRO", "CELO SILENCIO",
        "LECHONES MOMIFICADOS", "LECHONES NACIDOS BLANCOS", "TREMOR CONGENITO", "PELO HIRSUTO", "DIARREA VERDOSA",
        "PIEL PALIDA", "COLITIS CATARRAL", "MANCHAS ROJAS", "RONCHAS ROJIZAS", "EQUIMOSIS CUTANEA", "DERMATITIS",
        "EDEMA SUBCUTANEO", "HEMORRAGIA SUBCUTANEA", "CONSUMO DE ORINA", "POLISEROSITIS", "CORAZON BLANDO",
        "MENINGITIS", "HIDROPERICARDIO", "NEFRITIS INTERSTICIAL", "VEJIGA HERMORRAGICA", "VEJIGA ULCEROSA",
        "EDEMA RENAL", "HIPERPLASIA DE LINFONODULOS", "MUERTE SÚBITA", "HEPATOMEGALIA", "ESPLENOMEGALIA",
        "NEUMONIA INTERSTICIAL", "MANCHAS BLANCAS EN RIÑONES", "NECROSIS DEL MIOCARDIO"
    ),
    "Salmonelosis" to listOf(
        "DIARREA", "FIEBRE", "DESHIDRATACION", "LETARGO", "PÉRDIDA DE APETITO", "ANOREXIA", "POSTRACIÓN",
        "CIANOSIS", "DISNEA", "DIARREA AMARILLA", "DIARREA GRIS", "EDEMA DE VESICULA BILIAR", "DESHIDRATACION",
        "ABDOMEN PURPURA", "TOS PRODUCTIVA", "ENTEROCOLITIS", "TIFLITIS NECROTICA", "ESPLENOMEGALIA",
        "HEPATOMEGALIA", "NEUMONIA INTERTICIAL", "EDEMA PULMONAR", "HEMORRAGIA PULMONAR", "NECROSIS HEPATICA",
        "INFARTOS VENOSOS EN CURVATURA MAYOR DEL ESTOMAGO"
    ),
    "Brucelosis" to listOf(
        "ABORTOS", "ESTERILIDAD", "COJERA", "INFLAMACIÓN TESTICULAR", "ANESTRO (18-21 DIAS)", "ABORTO",
        "ENDOMETRITIS", "COJERA", "PARALISIS POSTERIOR", "METRITIS", "RETENCION PLACENTARIA",
        "DESCARGA VULVAR SANGUINOLENTA", "INCOORDINACIÓN", "TENDINITIS", "BURSITIS", "PLACENTITIS",
        "ABCESOS EN BAZO", "ABCESOS EN RIÑONES", "MASTITIS INTERSTICIAL", "EXTRACCION DIFICIL DE PLACENTA RETENIDA"
    ),
    "Erisipela" to listOf(
        "FIEBRE", "LESIONES CUTÁNEAS", "COJERA", "ABORTOS", "FIEBRE (40°c-42°c)", "ANOREXIA", "DISNEA",
        "URTICARIA ROMBOIDE", "ABORTO", "AGALACTIA", "LECHONES MOMIFICADOS", "HECES SECAS", "ARTRITIS",
        "TAQUICARDIA", "COJERA", "PETEQUIA RENAL", "PETEQUIA CARDICA", "ESPLENOMEGALIA", "HEPATOMEGALIA",
        "INFLAMACION HEMORRAGICA DE ESTOMAGO", "INFLAMACION HEMORRAGICA DE INTESTINO", "TROMBOSIS CORONARIA",
        "NECROSIS HEPATICA", "HIPERPLASIA LINFONODULAR", "MENINGITIS", "ENDOCARDITIS VEGETATIVA", "SINOVITIS"
    ),
    "Clostridiosis" to listOf(
        "DIARREA", "DEPRESIÓN", "DESHIDRATACIÓN", "MUERTE SÚBITA", "ANOREXIA", "DIARREA GRIS PASTOSA",
        "DIARREA HEMORRAGICA", "DECOLORACION DEL MUSCULO DORSAL", "PERDIDA DE PESO", "HINCHAZON DOLOROSA",
        "ENFISEMA DE YEYUNO", "GANGRENA GASEOSA", "INTESTINO DELGADO ROJO OBSCURO", "INTESTINO DELGADO TRANSPARENTE",
        "PRESENCIA DE GAS EN EL INTESTINO GRUESO", "NECROSIS DEL INTESTINO GRUESO", "MUERTE SUBITA",
        "HEPATOMEGALIA", "ESPLENOMEGALIA", "NECROSIS HEPATICA", "EDEMA DE VESICULA BILIAR"
    ),
    "ZEARALENONA" to listOf(
        "ABORTO EN CUALQUIER ETAPA", "LECHONES NACIDOS CON PATAS ABIERTAS (SPLAYLEGS)", "REDUCCIÓN DE CELO EN CERDAS",
        "ULCERAS EN LA PIEL", "MASTITIS INTERSTICIAL", "PSEUDOPREÑEZ"
    ),
    "AFLATOXINA" to listOf("ANOREXIA", "EQUIMOSIS"),
    "OCRATOXINA" to listOf("ANOREXIA", "POLIDIPSIA", "DIARREA", "RETRASO DEL CRECIMIENTO"),
    "TRICOTECENOS" to listOf("ANOREXIA", "RECHAZO DEL ALIMENTO", "LECHONES NACIDOS CON PATAS ABIERTAS (SPLAYLEGS)", "VOMITO", "DIARREA"),
    "FUMONISINA" to listOf("ANOREXIA", "RECHAZO DE ALIMENTO", "RETRASO DEL CRECIMIENTO", "ICTERICIA", "DISNEA", "TOS PRODUCTIVA"),
    "CAMPILOBACTERIOSIS" to listOf(
        "ANOREXIA", "DIARREA MUCOSA O CREMOSA", "DESHIDRATACION", "FIEBRE", "TENESMO", "VOMITO CON MANCHAS DE SANGRE",
        "DOLOR ABDOMINAL", "CALAMBRES ABDOMINALES"
    ),
    "COCCIDIOSIS" to listOf(
        "DIARREA GRASOSA", "DIARREA AMARILLENTA O BLANQUECINA", "ANOREXIA", "DEBILIDAD", "DESHIDRATACION",
        "OLOR ACIDO DEL EXCREMENTO", "TENESMO", "CAQUEXIA", "MUERTE", "PELO HIRSUTO", "RETRASO DEL CRECIMIENTO"
    ),
    "ASCARIS SUUM" to listOf(
        "ANOREXIA", "RETRASO DEL CRECIMIENTO", "ICTERICIA", "DISNEA", "TOS ASMATICA", "DIARREA AGUDA AMARILLA",
        "LORDOSIS", "DOLOR ABDOMINAL", "VIENTRE PROMINENTE", "RAQUITISMO", "DESNUTRICION", "CONVULSIONES"
    ),
    "ESTRONGILOIDES" to listOf("ANEMIA", "DIARREA AGUDA AMARILLA", "EMACIACION", "MUERTE SÚBITA", "TOS ASMATICA")
)

/**
 * Función para normalizar síntomas (eliminar acentos, mayúsculas, etc.)
 */
fun normalizarSintoma(sintoma: String): String {
    return sintoma.trim().uppercase()
        .replace("Á", "A").replace("É", "E").replace("Í", "I").replace("Ó", "O").replace("Ú", "U").replace("Ñ", "N")
        .replace("  ", " ")
}

/**
 * Función para buscar similitudes entre síntomas
 */
fun buscarSimilitud(sintomaUsuario: String, sintomaEnfermedad: String): Boolean {
    val normalizadoUsuario = normalizarSintoma(sintomaUsuario)
    val normalizadoEnfermedad = normalizarSintoma(sintomaEnfermedad)
    
    // Coincidencia exacta
    if (normalizadoUsuario == normalizadoEnfermedad) return true
    
    // Coincidencia parcial
    if (normalizadoUsuario.contains(normalizadoEnfermedad) || normalizadoEnfermedad.contains(normalizadoUsuario)) return true
    
    // Palabras clave comunes para búsqueda semántica
    val palabrasClave = mapOf(
        "FIEBRE" to listOf("FIEBRE", "FEBRIL", "TEMPERATURA"),
        "DIARREA" to listOf("DIARREA", "DIARREICA", "EVACUACION"),
        "VOMITO" to listOf("VOMITO", "VOMITOS", "EMESIS"),
        "TOS" to listOf("TOS", "TOSER", "TOSIDO"),
        "DOLOR" to listOf("DOLOR", "DOLOROSO", "DOLOROSA"),
        "ANOREXIA" to listOf("ANOREXIA", "FALTA DE APETITO", "INAPETENCIA"),
        "DEPRESION" to listOf("DEPRESION", "DEPRIMIDO", "APATIA"),
        "CONVULSIONES" to listOf("CONVULSIONES", "CONVULSION", "EPILEPSIA"),
        "COJERA" to listOf("COJERA", "COJO", "COJEAR"),
        "ARTRITIS" to listOf("ARTRITIS", "ARTICULAR", "ARTICULACION"),
        "ABORTO" to listOf("ABORTO", "ABORTAR", "ABORTOS"),
        "ANEMIA" to listOf("ANEMIA", "ANEMICO", "PALIDEZ"),
        "ICTERICIA" to listOf("ICTERICIA", "ICTERICO", "AMARILLO"),
        "DESHIDRATACION" to listOf("DESHIDRATACION", "DESHIDRATADO", "SECO"),
        "LETARGIA" to listOf("LETARGIA", "LETARGICO", "SOMNOLIENTO"),
        "DISNEA" to listOf("DISNEA", "DIFICULTAD RESPIRATORIA", "FALTA DE AIRE"),
        "EDEMA" to listOf("EDEMA", "HINCHAZON", "INFLAMACION"),
        "NECROSIS" to listOf("NECROSIS", "NECROTICO", "MUERTO"),
        "HEMORRAGIA" to listOf("HEMORRAGIA", "SANGRADO", "SANGRE"),
        "INFLAMACION" to listOf("INFLAMACION", "INFLAMADO", "HINCHADO"),
        "ULCERAS" to listOf("ULCERAS", "ULCERA", "LESION"),
        "DERMATITIS" to listOf("DERMATITIS", "PIEL", "CUTANEO"),
        "MENINGITIS" to listOf("MENINGITIS", "MENINGEO", "CEREBRAL"),
        "NEUMONIA" to listOf("NEUMONIA", "PULMONAR", "RESPIRATORIO"),
        "ENTERITIS" to listOf("ENTERITIS", "INTESTINAL", "DIGESTIVO"),
        "MASTITIS" to listOf("MASTITIS", "MAMARIO", "UBRE"),
        "METRITIS" to listOf("METRITIS", "UTERINO", "VAGINAL"),
        "ORQUITIS" to listOf("ORQUITIS", "TESTICULAR", "ESCROTAL")
    )
    
    // Buscar coincidencias por palabras clave
    for ((clave, sinonimos) in palabrasClave) {
        if (sinonimos.any { normalizadoUsuario.contains(it) } && 
            sinonimos.any { normalizadoEnfermedad.contains(it) }) {
            return true
        }
    }
    
    return false
}

/**
 * Función para generar el mapeo completo
 */
fun generarMapeoCompleto(): Map<String, List<String>> {
    val mapeoCompleto = mutableMapOf<String, MutableList<String>>()
    
    // Inicializar todos los síntomas con listas vacías
    sintomasUsuario.forEach { sintoma ->
        mapeoCompleto[sintoma] = mutableListOf()
    }
    
    // Buscar enfermedades para cada síntoma
    sintomasUsuario.forEach { sintomaUsuario ->
        enfermedadesConSintomas.forEach { (enfermedad, sintomasEnfermedad) ->
            sintomasEnfermedad.forEach { sintomaEnfermedad ->
                if (buscarSimilitud(sintomaUsuario, sintomaEnfermedad)) {
                    if (!mapeoCompleto[sintomaUsuario]!!.contains(enfermedad)) {
                        mapeoCompleto[sintomaUsuario]!!.add(enfermedad)
                    }
                }
            }
        }
    }
    
    return mapeoCompleto
}

/**
 * Función para generar JSON formateado
 */
fun generarJSON(mapeo: Map<String, List<String>>): String {
    val jsonBuilder = StringBuilder()
    jsonBuilder.append("{\n")
    jsonBuilder.append("  \"symptomToDiseases\": {\n")
    
    val entries = mapeo.entries.toList()
    entries.forEachIndexed { index, (sintoma, enfermedades) ->
        jsonBuilder.append("    \"$sintoma\": [\n")
        if (enfermedades.isNotEmpty()) {
            enfermedades.forEachIndexed { i, enfermedad ->
                val coma = if (i < enfermedades.size - 1) "," else ""
                jsonBuilder.append("      \"$enfermedad\"$coma\n")
            }
        }
        val coma = if (index < entries.size - 1) "," else ""
        jsonBuilder.append("    ]$coma\n")
    }
    
    jsonBuilder.append("  }\n")
    jsonBuilder.append("}")
    
    return jsonBuilder.toString()
}

/**
 * Función principal que ejecuta todo el proceso
 */
fun main() {
    println("=== GENERADOR AUTOMÁTICO DE MAPEO SÍNTOMAS-ENFERMEDADES ===")
    println("Iniciando proceso de generación...")
    
    // Generar mapeo
    val mapeoCompleto = generarMapeoCompleto()
    
    // Calcular estadísticas
    val totalSintomas = mapeoCompleto.size
    val sintomasConEnfermedades = mapeoCompleto.count { it.value.isNotEmpty() }
    val sintomasSinEnfermedades = mapeoCompleto.count { it.value.isEmpty() }
    val totalEnfermedades = mapeoCompleto.values.flatten().distinct().size
    
    // Generar JSON
    val json = generarJSON(mapeoCompleto)
    
    // Guardar archivo
    val nombreArchivo = "symptom_disease_mapping_complete.json"
    File(nombreArchivo).writeText(json)
    
    // Mostrar resultados
    println("\n=== RESULTADOS ===")
    println("✅ Archivo generado: $nombreArchivo")
    println("📊 Estadísticas:")
    println("   • Total de síntomas: $totalSintomas")
    println("   • Síntomas con enfermedades asociadas: $sintomasConEnfermedades")
    println("   • Síntomas sin enfermedades asociadas: $sintomasSinEnfermedades")
    println("   • Total de enfermedades únicas: $totalEnfermedades")
    println("   • Tamaño del archivo: ${json.length} caracteres")
    
    // Mostrar síntomas sin enfermedades (primeros 10)
    if (sintomasSinEnfermedades > 0) {
        println("\n⚠️  Síntomas sin enfermedades asociadas (primeros 10):")
        mapeoCompleto.filter { it.value.isEmpty() }.keys.take(10).forEach { 
            println("   • $it") 
        }
        if (sintomasSinEnfermedades > 10) {
            println("   ... y ${sintomasSinEnfermedades - 10} más")
        }
    }
    
    // Mostrar ejemplos de mapeo exitoso
    println("\n✅ Ejemplos de mapeo exitoso:")
    mapeoCompleto.filter { it.value.isNotEmpty() }.take(5).forEach { (sintoma, enfermedades) ->
        println("   • $sintoma → ${enfermedades.joinToString(", ")}")
    }
    
    println("\n🎉 ¡Proceso completado exitosamente!")
    println("💡 El archivo JSON está listo para ser usado en tu aplicación Android.")
} 